import type { ThemeAdapter } from "./types"

export const antdAdapter: ThemeAdapter = {
  name: "antd",
  config: { framework: "antd", primary: "#7c5cff", mode: "dark" },
  classes: {
    btn: "ant-btn",
    btnPrimary: "ant-btn-primary",
    btnGhost: "ant-btn-default ant-btn-background-ghost",
    btnSm: "ant-btn-sm",
    btnLg: "ant-btn-lg",
    card: "ant-card",
    cardHover: "",
    cardIcon: "",
    input: "ant-input",
    inputError: "ant-input-status-error",
    label: "ant-form-item-label",
    table: "ant-table",
    tableHead: "ant-table-thead",
    tableRow: "ant-table-row",
    tableCell: "ant-table-cell",
    badge: "ant-badge",
    badgeSuccess: "ant-badge-status-success",
    badgeWarning: "ant-badge-status-warning",
    badgeError: "ant-badge-status-error",
    modal: "ant-modal",
    modalOverlay: "ant-modal-mask",
    modalContent: "ant-modal-content",
    modalHeader: "ant-modal-header",
    modalBody: "ant-modal-body",
    modalFooter: "ant-modal-footer",
    nav: "ant-menu-horizontal",
    navLink: "ant-menu-item",
    navLinkActive: "ant-menu-item-selected",
    sidebar: "ant-layout-sider",
    sidebarLink: "ant-menu-item",
    sidebarLinkActive: "ant-menu-item-selected",
    mainContent: "ant-layout-content",
    formGroup: "ant-form-item",
    formError: "ant-form-item-explain-error",
    checkbox: "ant-checkbox",
    radio: "ant-radio",
    switch_: "ant-switch",
    tabs: "ant-tabs",
    tab: "ant-tabs-tab",
    tabActive: "ant-tabs-tab-active",
    spinner: "ant-spin",
    toast: "ant-message",
    toastSuccess: "",
    toastError: "",
    alert: "ant-alert",
    alertInfo: "ant-alert-info",
    alertSuccess: "ant-alert-success",
    alertWarning: "ant-alert-warning",
    alertError: "ant-alert-error",
    tooltip: "ant-tooltip",
    dropdown: "ant-dropdown",
    dropdownItem: "ant-dropdown-menu-item",
    divider: "ant-divider",
    progress: "ant-progress",
    empty: "ant-empty",
    pagination: "ant-pagination",
    pageItem: "ant-pagination-item",
    pageActive: "ant-pagination-item-active",
  },
  components: {
    button: "Button",
    table: "Table",
    modal: "Modal",
    toast: "message",
    dropdown: "Dropdown",
    tooltip: "Tooltip",
    tabs: "Tabs",
    spinner: "Spin",
    alert: "Alert",
    badge: "Badge",
    checkbox: "Checkbox",
    radio: "Radio",
    switch_: "Switch",
    progress: "Progress",
    pagination: "Pagination",
    icon: "Icon",
  },
  getDependencies() { return ["antd", "@ant-design/icons"] },
  getImports() { return `import { Button, Table, Modal, message, Dropdown, Tooltip, Tabs, Spin, Alert, Badge, Checkbox, Radio, Switch, Progress, Pagination } from "antd"\nimport * as Icons from "@ant-design/icons"` },
  getProvider() { return `import { ConfigProvider, theme } from "antd"\n\nexport function ZoruxThemeProvider({ children }: { children: React.ReactNode }) {\n  return (\n    <ConfigProvider theme={{ algorithm: theme.darkAlgorithm, token: { colorPrimary: "#7c5cff" } }}>\n      {children}\n    </ConfigProvider>\n  )\n}` },
}
