import type { ThemeAdapter } from "./types"

export const daisyUIAdapter: ThemeAdapter = {
  name: "daisyui",
  config: { framework: "daisyui", primary: "#a855f7", mode: "dark" },
  classes: {
    btn: "btn",
    btnPrimary: "btn-primary",
    btnGhost: "btn-ghost",
    btnSm: "btn-sm",
    btnLg: "btn-lg",
    card: "card bg-base-100 shadow-xl",
    cardHover: "hover:shadow-2xl transition-shadow",
    cardIcon: "",
    input: "input input-bordered w-full",
    inputError: "input-error",
    label: "label-text",
    table: "table table-zebra w-full",
    tableHead: "",
    tableRow: "",
    tableCell: "",
    badge: "badge",
    badgeSuccess: "badge-success",
    badgeWarning: "badge-warning",
    badgeError: "badge-error",
    modal: "modal modal-open",
    modalOverlay: "modal-backdrop",
    modalContent: "modal-box",
    modalHeader: "",
    modalBody: "",
    modalFooter: "modal-action",
    nav: "",
    navLink: "link link-hover",
    navLinkActive: "link text-primary",
    sidebar: "",
    sidebarLink: "link link-hover",
    sidebarLinkActive: "link text-primary font-semibold",
    mainContent: "",
    formGroup: "form-control",
    formError: "text-error text-sm",
    checkbox: "checkbox",
    radio: "radio",
    switch_: "toggle",
    tabs: "tabs tabs-box",
    tab: "tab",
    tabActive: "tab-active",
    spinner: "loading loading-spinner loading-md",
    toast: "alert alert-info",
    toastSuccess: "alert-success",
    toastError: "alert-error",
    alert: "alert",
    alertInfo: "alert-info",
    alertSuccess: "alert-success",
    alertWarning: "alert-warning",
    alertError: "alert-error",
    tooltip: "tooltip",
    dropdown: "dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52",
    dropdownItem: "",
    divider: "divider",
    progress: "progress progress-primary w-full",
    empty: "",
    pagination: "join",
    pageItem: "join-item btn btn-sm",
    pageActive: "btn-active",
  },
  components: {
    button: "Button", table: "Table", modal: "Modal", toast: "Alert",
    dropdown: "Dropdown", tooltip: "Tooltip", tabs: "Tabs", spinner: "Loading",
    alert: "Alert", badge: "Badge", checkbox: "Checkbox", radio: "Radio",
    switch_: "Toggle", progress: "Progress", pagination: "Join", icon: "Icon",
  },
  getDependencies() { return ["daisyui", "tailwindcss", "postcss", "autoprefixer"] },
  getImports() { return "" },
  getProvider() { return `import "daisyui/dist/full.css"\n\nexport function ZoruxThemeProvider({ children }: { children: React.ReactNode }) {\n  return <div data-theme="dark">{children}</div>\n}` },
  getTailwindConfig() {
    return `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx}", "./views/**/*.{ts,tsx}"],
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        dark: {
          ...require("daisyui/src/theming/themes")["dark"],
          primary: "#a855f7",
          "--rounded-btn": "0.5rem",
        },
      },
    ],
  },
}`
  },
}
