import type { ThemeAdapter } from "./types"

export const muiAdapter: ThemeAdapter = {
  name: "mui",
  config: { framework: "mui", primary: "#7c5cff", mode: "dark" },
  classes: {
    btn: "MuiButton-root", btnPrimary: "MuiButton-contained", btnGhost: "MuiButton-outlined",
    btnSm: "MuiButton-sizeSmall", btnLg: "MuiButton-sizeLarge",
    card: "MuiCard-root", cardHover: "", cardIcon: "",
    input: "MuiInputBase-root MuiOutlinedInput-root", inputError: "Mui-error",
    label: "MuiInputLabel-root", table: "MuiTable-root",
    tableHead: "MuiTableHead-root", tableRow: "MuiTableRow-root",
    tableCell: "MuiTableCell-root",
    badge: "MuiBadge-root", badgeSuccess: "", badgeWarning: "", badgeError: "",
    modal: "MuiModal-root", modalOverlay: "MuiBackdrop-root",
    modalContent: "MuiPaper-root MuiDialog-paper",
    modalHeader: "", modalBody: "", modalFooter: "",
    nav: "", navLink: "", navLinkActive: "", sidebar: "",
    sidebarLink: "", sidebarLinkActive: "", mainContent: "",
    formGroup: "", formError: "", checkbox: "MuiCheckbox-root",
    radio: "MuiRadio-root", switch_: "MuiSwitch-root",
    tabs: "MuiTabs-root", tab: "MuiTab-root", tabActive: "Mui-selected",
    spinner: "MuiCircularProgress-root",
    toast: "", toastSuccess: "", toastError: "",
    alert: "MuiAlert-root", alertInfo: "MuiAlert-standardInfo",
    alertSuccess: "MuiAlert-standardSuccess", alertWarning: "MuiAlert-standardWarning",
    alertError: "MuiAlert-standardError",
    tooltip: "MuiTooltip-root", dropdown: "MuiMenu-root",
    dropdownItem: "MuiMenuItem-root", divider: "MuiDivider-root",
    progress: "MuiLinearProgress-root", empty: "", pagination: "MuiPagination-root",
    pageItem: "MuiPaginationItem-root", pageActive: "Mui-selected",
  },
  components: {
    button: "Button", table: "Table", modal: "Dialog", toast: "Snackbar",
    dropdown: "Menu", tooltip: "Tooltip", tabs: "Tabs", spinner: "CircularProgress",
    alert: "Alert", badge: "Badge", checkbox: "Checkbox", radio: "Radio",
    switch_: "Switch", progress: "LinearProgress", pagination: "Pagination", icon: "Icon",
  },
  getDependencies() { return ["@mui/material", "@emotion/react", "@emotion/styled", "@mui/icons-material"] },
  getImports() { return `import { Button, Table, Dialog, Snackbar, Menu, Tooltip, Tabs, Tab, CircularProgress, Alert, Badge, Checkbox, Radio, Switch, LinearProgress, Pagination } from "@mui/material"\nimport * as Icons from "@mui/icons-material"` },
  getProvider() { return `import { ThemeProvider, createTheme, CssBaseline } from "@mui/material"\n\nconst theme = createTheme({ palette: { mode: "dark", primary: { main: "#7c5cff" } } })\n\nexport function ZoruxThemeProvider({ children }: { children: React.ReactNode }) {\n  return (\n    <ThemeProvider theme={theme}>\n      <CssBaseline />\n      {children}\n    </ThemeProvider>\n  )\n}` },
}
