import { readFileSync, existsSync, writeFileSync, mkdirSync, readdirSync } from "fs"
import { join } from "path"
import { load } from "js-yaml"

export async function contextCommand(args: string[]) {
  const rootDir = process.cwd()
  const appYamlPath = join(rootDir, "app.yaml")

  if (!existsSync(appYamlPath)) {
    console.error("[Zorux] No app.yaml found")
    process.exit(1)
  }

  const config = load(readFileSync(appYamlPath, "utf-8")) as any
  const models = config.models || {}
  const modelNames = Object.keys(models)
  const budgetArg = args.find(a => a.startsWith("--budget="))
  const budget = budgetArg ? parseInt(budgetArg.split("=")[1]) : 0
  const outputArg = args.find(a => a.startsWith("--output="))
  const outputPath = outputArg ? join(process.cwd(), outputArg.split("=")[1]) : null

  const lines: string[] = []
  const w = (s: string) => lines.push(s)

  // Compact mode for low budget
  if (budget > 0 && budget < 3000) {
    w(`# ${config.name || "Zorux App"} — Context (${budget}t budget)`)
    w(``)
    w(`Type: ${config.type || "api"}`)
    w(`Database: ${config.database?.provider || "sqlite"}`)
    w(`Models: ${modelNames.join(", ") || "none"}`)
    if (config.auth) w(`Auth: ${config.auth.model} (${config.auth.registration})`)
    w(``)
    w(`## Quick commands`)
    w(`zorux dev          — Start dev server`)
    w(`zorux verify       — Validate project`)
    w(`zorux explain      — Full generation plan`)
    w(`zorux inspect --json — Generate manifest`)
    if (modelNames.length > 0) {
      w(``)
      w(`## Models`)
      for (const name of modelNames) {
        const m = models[name]
        const fields = Object.keys(m.fields || {}).join(", ")
        w(`- ${name}${m.auth ? " 🔐" : ""}: ${fields}`)
      }
    }
  } else if (budget > 0 && budget < 8000) {
    // Medium context
    w(`# ${config.name || "Zorux App"} — Context (${budget}t budget)`)
    w(``)
    w(`## Overview`)
    w(`- Type: ${config.type || "api"}`)
    w(`- Database: ${config.database?.provider || "sqlite"}`)
    w(`- Auth: ${config.auth ? `${config.auth.model} (${config.auth.registration})` : "none"}`)
    w(`- Models: ${modelNames.length}`)
    w(`- Plugins: ${(config.plugins || []).length}`)
    w(``)
    w(`## Models`)
    for (const name of modelNames) {
      const m = models[name]
      const fields = Object.keys(m.fields || {})
      const policies = m.policies || {}
      w(`### ${name}${m.auth ? " (auth)" : ""}`)
      w(`Fields: ${fields.join(", ")}`)
      if (Object.keys(policies).length > 0) {
        for (const [action, policy] of Object.entries(policies)) {
          w(`- ${action}: ${policy}`)
        }
      }
      if (m.timestamps) w(`- timestamps: true`)
      if (m.scoped) w(`- scoped (multi-tenant)`)
    }
    w(``)
    w(`## Editable files`)
    w(`- app.yaml`)
    w(`- actions/*.ts`)
    w(`- plugins/*.ts`)
  } else {
    // Full context
    w(`# ${config.name || "Zorux App"} — Complete Context`)
    w(``)
    w(`> Generated by zorux context`)
    w(`> Run \`zorux context --budget 2000\` for compact version`)
    w(``)
    w(`## Overview`)
    w(`- **Name:** ${config.name || "unnamed"}`)
    w(`- **Type:** ${config.type || "api"}`)
    w(`- **Database:** ${config.database?.provider || "sqlite"}`)
    if (config.database?.url) w(`- **Database URL:** ${config.database.url}`)
    w(`- **Cache:** ${config.cache?.provider || "none"}`)
    w(`- **Email:** ${config.email?.provider || "none"}`)
    w(`- **Auth:** ${config.auth ? `${config.auth.model} (${config.auth.registration})` : "none"}`)
    w(`- **Realtime:** ${config.realtime?.enabled ? "enabled" : "disabled"}`)
    w(`- **Plugins:** ${(config.plugins || []).length}`)
    w(``)
    w(`## Models (${modelNames.length})`)
    w(``)
    for (const name of modelNames) {
      const m = models[name]
      const fields = m.fields || {}
      const policies = m.policies || {}
      w(`### ${name}${m.auth ? " (🔐 auth)" : ""}`)
      w(``)
      w(`| Field | Type | Constraints |`)
      w(`|-------|------|-------------|`)
      for (const [fname, ftype] of Object.entries(fields)) {
        w(`| ${fname} | ${ftype} | ${m.required?.includes(fname) ? "required" : ""} ${String(ftype).includes("unique") ? "unique" : ""} |`)
      }
      w(``)
      if (Object.keys(policies).length > 0) {
        w(`**Policies:**`)
        for (const [action, policy] of Object.entries(policies)) {
          w(`- \`${action}\`: \`${policy}\``)
        }
        w(``)
      }
      if (m.timestamps) w(`- Timestamps: created_at, updated_at`)
      if (m.scoped) w(`- Scoped (multi-tenant)`)
      if (m.softDelete) w(`- Soft delete`)
      if (m.seed) w(`- Seed: ${m.seed} records`)
    }
    w(``)
    w(`## Auth Configuration`)
    if (config.auth) {
      w(`- **Model:** ${config.auth.model}`)
      w(`- **Registration:** ${config.auth.registration}`)
      w(`- **Roles:** ${(config.auth.roles || []).join(", ")}`)
      if (config.auth.organization?.enabled) {
        w(`- **Organizations:** enabled`)
        w(`  - Org roles: ${(config.auth.organization.roles || []).join(", ")}`)
      }
      w(`- **Password min length:** ${config.auth.passwordMinLength || 8}`)
      w(`- **Social providers:** ${Object.keys(config.auth.social || {}).join(", ") || "none"}`)
      w(``)
      w(`**Auth routes:**`)
      w(`- POST /api/auth/register`)
      w(`- POST /api/auth/login`)
      w(`- GET /api/auth/me`)
      w(`- POST /api/auth/logout`)
    } else {
      w(`- Auth not enabled`)
    }
    w(``)
    w(`## API Routes`)
    w(`- Health: GET /api/health`)
    for (const name of modelNames) {
      const plural = (models[name]?.plural || name.toLowerCase() + "s").replace(/ss$/, "s")
      w(`- CRUD \`${name}\`: GET/POST /api/${plural}, GET/PUT/DELETE /api/${plural}/:id`)
    }
    if (config.graphql) w(`- GraphQL: POST /api/graphql`)
    if (config.type !== "api") {
      w(`- Admin: GET /admin`)
      w(`- Login: GET /login`)
      w(`- Register: GET /register`)
    }
    w(``)
    w(`## File Structure`)
    w(``)
    w(`\`\`\``)
    w(`📁 ${config.name || "project"}/`)
    w(`  📄 app.yaml          ← main config (edit this)`)
    w(`  📄 package.json`)
    w(`  📄 .env`)
    if (existsSync(join(rootDir, "web", "pages"))) {
      w(`  📁 web/pages/        ← public pages (auto-loaded)`)
      const pages = readdirSync(join(rootDir, "web", "pages"))
      for (const p of pages.filter(f => f.endsWith(".tsx"))) {
        w(`    📄 ${p}`)
      }
    }
    if (existsSync(join(rootDir, "actions"))) {
      w(`  📁 actions/          ← custom actions`)
      const acts = readdirSync(join(rootDir, "actions"))
      for (const a of acts.filter(f => f.endsWith(".ts"))) {
        w(`    📄 ${a}`)
      }
    }
    if (existsSync(join(rootDir, "plugins"))) {
      w(`  📁 plugins/          ← plugins`)
    }
    w(`\`\`\``)
    w(``)
    w(`## CLI Commands`)
    w(`- \`zorux dev\`             — Start dev server`)
    w(`- \`zorux verify\`          — Validate project`)
    w(`- \`zorux doctor\`          — Diagnostic`)
    w(`- \`zorux explain\`         — Generation plan`)
    w(`- \`zorux inspect --json\`  — Generate manifest.json`)
    w(`- \`zorux context\`         — This file`)
    w(`- \`zorux recipe add\`      — Apply recipe`)
    w(`- \`zorux db migrate\`      — Run migrations`)
    w(`- \`zorux seed\`            — Seed data`)
    w(`- \`zorux test\`            — Run tests`)
    w(``)
    w(`## Agent Instructions`)
    w(`- Source of truth: \`app.yaml\``)
    w(`- Prefer Zorux CLI over npm/npx`)
    w(`- Do NOT hand-write CRUD, auth, or admin — they are auto-generated`)
    w(`- Use \`plugins/*.ts\` for custom routes, \`actions/*.ts\` for custom handlers`)
    w(`- Run \`zorux verify\` after any change to \`app.yaml\``)
    w(`- Read \`AGENTS.md\` for full agent instructions`)
  }

  const content = lines.join("\n")

  // Output to file or stdout
  if (outputPath) {
    mkdirSync(join(rootDir, ".zorux"), { recursive: true })
    writeFileSync(outputPath, content, "utf-8")
    const tokens = approximateTokens(content)
    console.log(`\n  📋 Context written to ${outputPath}`)
    console.log(`  📊 ~${tokens} tokens\n`)
  } else {
    console.log(content)
  }
}

function approximateTokens(text: string): number {
  // Rough estimate: ~4 chars per token for English text
  return Math.ceil(text.length / 4)
}
