import { mkdirSync, writeFileSync, existsSync } from 'fs'
import { join } from 'path'

export async function newCommand(name: string, options: { api?: boolean; web?: boolean; mobile?: boolean; fullstack?: boolean; saas?: boolean; all?: boolean; ui?: string }) {
  const projectDir = join(process.cwd(), name)

  if (existsSync(projectDir)) {
    console.error('[Zorux] Directory ' + name + ' already exists')
    process.exit(1)
  }

  const isSaaS = options.saas || options.all
  const mode = options.all ? 'fullstack' : (isSaaS ? 'fullstack' : (options.fullstack ? 'fullstack' : (options.mobile ? 'mobile' : (options.web ? 'web' : 'api'))))

  console.log('\n  \u26a1 Creating ' + (isSaaS ? 'SaaS ' : '') + mode + ' project: ' + name + '\n')

  mkdirSync(join(projectDir, 'actions'), { recursive: true })
  mkdirSync(join(projectDir, 'public'), { recursive: true })
  mkdirSync(join(projectDir, 'jobs'), { recursive: true })

  if (mode === 'web' || mode === 'fullstack') {
    mkdirSync(join(projectDir, 'web', 'pages'), { recursive: true })
    mkdirSync(join(projectDir, 'web', 'components'), { recursive: true })
  }

  writeFileSync(join(projectDir, 'app.yaml'), isSaaS ? generateSaaSYaml(name) : generateAppYaml(name, mode))

  const pkg: any = {
    name,
    type: 'module',
    scripts: { dev: 'fw dev', build: 'fw build' },
    dependencies: {
      Zorux: '^0.1.0',
      'drizzle-orm': '^0.33.0',
      hono: '^4.5.0',
      zod: '^3.23.0',
    },
    devDependencies: { 'bun-types': 'latest', typescript: '^5.5.0' },
  }

  // Add UI framework dependencies if specified
  if (options.ui && options.ui !== "default") {
    try {
      const { getUIDependencies } = await import("../core/theme")
      const deps = getUIDependencies(options.ui)
      for (const dep of deps) {
        pkg.dependencies[dep] = "*"
      }
      pkg.scripts["dev"] = "zorux dev"
      pkg.scripts["build"] = "zorux build"
    } catch {}
  }
  writeFileSync(join(projectDir, 'package.json'), JSON.stringify(pkg, null, 2))

  const tsconfig = {
    compilerOptions: {
      target: 'ESNext',
      module: 'ESNext',
      moduleResolution: 'bundler',
      strict: true,
      jsx: 'react-jsx',
      jsxImportSource: 'hono/jsx',
      types: ['bun-types'],
    },
    include: ['**/*.ts', '**/*.tsx'],
  }
  writeFileSync(join(projectDir, 'tsconfig.json'), JSON.stringify(tsconfig, null, 2))

  // SaaS extras
  if (isSaaS) {
    generateSaaSExtras(projectDir, name)
  } else {
    writeFileSync(join(projectDir, 'actions', '.gitkeep'), '')
  }

  if (!isSaaS) {
    const envExample = [
      '# Zorux - Environment Variables',
      '# Copy this file to .env and fill in your values',
      '',
      'PORT=3000',
      'JWT_SECRET=change-this-to-a-random-secret',
      '# DATABASE_URL=sqlite://data.db',
      '# For PostgreSQL:',
      '# DATABASE_URL=postgres://user:pass@localhost:5432/mydb',
      '# For Supabase:',
      '# SUPABASE_URL=https://xyz.supabase.co',
      '# SUPABASE_ANON_KEY=your-anon-key',
      '# SUPABASE_SERVICE_KEY=your-service-role-key',
    ].join('\n')
    writeFileSync(join(projectDir, '.env.example'), envExample)
    writeFileSync(join(projectDir, '.env'), envExample.replace('# Copy this file to .env and fill in your values', 'Generated by Zorux. Edit as needed.'))
  }

  // Generate mobile for --all
  if (options.all) {
    try {
      const { genMobileCommand } = await import("./gen-mobile")
      console.log("  Generating mobile app...")
      genMobileCommand(projectDir)
    } catch (err: any) {
      console.log("  - Mobile generation error:", err.message)
      console.log("zorux gen mobile' later")
    }
  }

  console.log('  \u2705 Created ' + name + ' at ' + projectDir)
  console.log('\n  Next steps:')
  console.log('    cd ' + name)
  console.log('    fw dev\n')
}

function generateAppYaml(name: string, mode: string): string {
  return '# ' + name + ' - Zorux ' + mode + ' app\n' +
'name: ' + name + '\n' +
'type: ' + mode + '\n' +
'provider: Zorux\n\n' +
'database:\n' +
'  provider: sqlite\n\n' +
'models:\n' +
'  # Add your models here\n' +
'  # Example:\n' +
'  # User:\n' +
'  #   fields:\n' +
'  #     name: string required\n' +
'  #     email: email unique\n' +
'  #   auth: password\n'
}

function generateSaaSYaml(name: string): string {
  return `# ${name} - SaaS app powered by Zorux
name: ${name}
type: fullstack
provider: Zorux

database:
  provider: sqlite

auth:
  model: User
  registration: open
  roles: [admin, viewer]
  defaultRole: viewer
  organization:
    enabled: true
    roles: [owner, admin, member]
    inviteExpiresIn: 7

models:
  User:
    fields:
      name: string required min:2
      email: string unique
    auth: password
    policies:
      list: admin
      read: authenticated
      update: owner
      delete: admin

  Project:
    fields:
      name: string required
      description: text
      org: Organization
    timestamps: true
    scoped: true
    policies:
      list: authenticated
      create: authenticated
      update: owner
      delete: admin

  Subscription:
    fields:
      plan: string enum:free,pro,enterprise
      status: string enum:active,canceled,past_due
      stripeCustomerId: string
      stripeSubscriptionId: string
      org: Organization
    timestamps: true
    scoped: true
    policies:
      list: admin
      read: authenticated
      update: admin
      delete: admin
`
}

function generateSaaSExtras(projectDir: string, name: string) {
  // -- Seed data file --
  writeFileSync(join(projectDir, "seed.ts"), `import { fw } from "Zorux"

export default async function seed() {
  // Create plans
  const plans = [
    { name: "Free", price: 0, features: "1 project, 3 members" },
    { name: "Pro", price: 29, features: "Unlimited projects, 10 members" },
    { name: "Enterprise", price: 99, features: "Everything, priority support" },
  ]

  console.log("  Seed data created!")
}
`)

  // -- Example action --
  writeFileSync(join(projectDir, "actions", "billing.ts"), `import { sendEmail } from "Zorux/email"

export const invoicePaid = {
  policy: "*",
  handler: async (c: any) => {
    const { email, amount } = await c.req.json()
    await sendEmail({
      to: email,
      subject: "Payment received",
      text: \`Thank you! We received \${amount}.\`,
    })
    return c.json({ success: true })
  },
}
`)

  // -- Example job --
  writeFileSync(join(projectDir, "jobs", "subscriptions.ts"), `export default {
  name: "check-expired-subscriptions",
  async perform(_args: any) {
    console.log("Checking for expired subscriptions...")
    // Check and update expired subscriptions
  },
}
`)

  // -- Landing page --
  writeFileSync(join(projectDir, "web", "pages", "landing.tsx"), `import type { FC } from "hono/jsx"

export const LandingPage: FC<{ appName: string }> = ({ appName }) => (
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>{appName}</title>
      <style>{":root{--primary:#3b82f6;--bg:#fff;--text:#111}body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;margin:0;padding:0;background:var(--bg);color:var(--text)}.hero{text-align:center;padding:6rem 2rem 4rem}.hero h1{font-size:3rem;margin:0}.hero p{font-size:1.2rem;color:#666;margin:1rem 0 2rem}.btn{display:inline-block;padding:0.75rem 2rem;background:var(--primary);color:#fff;text-decoration:none;border-radius:6px;font-weight:600}.features{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:2rem;padding:2rem;max-width:1000px;margin:0 auto}.feature{padding:1.5rem;border:1px solid #eee;border-radius:8px}.feature h3{margin:0 0 0.5rem}.footer{text-align:center;padding:2rem;color:#999;font-size:0.9rem}"}</style>
    </head>
    <body>
      <div class="hero">
        <h1>{appName}</h1>
        <p>Built with Zorux Framework � full-stack, auth, payments, teams.</p>
        <a href="/login" class="btn">Get Started</a>
      </div>
      <div class="features">
        <div class="feature"><h3>Team Management</h3><p>Invite members, assign roles, manage permissions.</p></div>
        <div class="feature"><h3>Subscriptions</h3><p>Stripe/Polar integration with plans and billing.</p></div>
        <div class="feature"><h3>API Keys</h3><p>Generate and manage API keys for integrations.</p></div>
      </div>
      <div class="footer">&copy; {new Date().getFullYear()} {appName}</div>
    </body>
  </html>
)
`)

  // -- Enhanced .env for SaaS --
  const envSaas = [
    "# Zorux - SaaS Environment",
    "",
    "PORT=3000",
    "JWT_SECRET=change-this-to-a-random-secret-please",
    "BASE_URL=http://localhost:3000",
    "APP_NAME=" + name,
    "EMAIL_PROVIDER=fake",
    "EMAIL_FROM=noreply@" + name.toLowerCase().replace(/\s+/g, "") + ".com",
    "",
    "# Stripe (optional)",
    "# STRIPE_SECRET_KEY=sk_live_...",
    "# STRIPE_WEBHOOK_SECRET=whsec_...",
    "",
    "# PostgreSQL (optional, default: SQLite)",
    "# DATABASE_URL=postgres://user:pass@localhost:5432/" + name,
  ].join("\n")
  writeFileSync(join(projectDir, ".env"), envSaas)
  writeFileSync(join(projectDir, ".env.example"), envSaas)

  console.log("  - Created SaaS template files")
  console.log("  - Created web/pages/landing.tsx (landing page)")
  console.log("  - Created actions/billing.ts (example action)")
  console.log("  - Created jobs/subscriptions.ts (example job)")
  console.log("  - Created seed.ts (data seeding)")
}
