import { readFileSync, existsSync, writeFileSync, mkdirSync, readdirSync } from "fs"
import { join } from "path"
import { load } from "js-yaml"

export async function snapshotCommand(args: string[]) {
  const rootDir = process.cwd()
  const appYamlPath = join(rootDir, "app.yaml")

  if (!existsSync(appYamlPath)) {
    console.error("[Zorux] No app.yaml found")
    process.exit(1)
  }

  const config = load(readFileSync(appYamlPath, "utf-8")) as any
  const models = config.models || {}
  const modelNames = Object.keys(models)

  const lines: string[] = []
  const w = (s: string) => lines.push(s)

  w(`# ${config.name || "Zorux App"} — Snapshot`)
  w(`> ${new Date().toISOString().split("T")[0]}`)
  w(``)
  w(`App: **${config.name || "unnamed"}**`)
  w(`Type: **${config.type || "api"}**`)
  w(`Database: **${config.database?.provider || "sqlite"}**`)
  w(`Auth: ${config.auth ? `**${config.auth.model}** (${config.auth.registration})` : "none"}`)
  w(`Models: **${modelNames.length}**`)

  if (modelNames.length > 0) {
    w(``)
    w(`## Models`)
    for (const name of modelNames) {
      const m = models[name]
      const fields = Object.keys(m.fields || {}).join(", ")
      const refs = modelNames.filter(n => {
        const fm = models[n]?.fields || {}
        return Object.values(fm).some((v: any) => typeof v === "string" && v === name)
      })
      w(`- **${name}**${m.auth ? " 🔐" : ""}: ${fields}`)
      if (refs.length > 0) w(`  - Referenced by: ${refs.join(", ")}`)
      if (m.scoped) w(`  - Scoped (multi-tenant)`)
      if (m.softDelete) w(`  - Soft delete`)
    }
  }

  if (config.plugins?.length > 0) {
    w(``)
    w(`Plugins: ${config.plugins.join(", ")}`)
  }

  // Routes count
  const routeCount = modelNames.length * 5 + (config.auth ? 4 : 0) + (config.type !== "api" ? 5 : 0)
  w(``)
  w(`Routes: ~${routeCount} generated`)

  // Custom files count
  let customCount = 0
  for (const dir of ["actions", "jobs", "plugins"]) {
    const d = join(rootDir, dir)
    if (existsSync(d)) customCount += readdirSync(d).filter(f => f.endsWith(".ts")).length
  }
  const webPages = join(rootDir, "web", "pages")
  if (existsSync(webPages)) customCount += readdirSync(webPages).filter(f => f.endsWith(".tsx")).length
  if (customCount > 0) w(`Custom files: ${customCount}`)

  // Warnings
  const warnings: string[] = []
  if (config.auth && !models[config.auth.model]) warnings.push(`Auth model "${config.auth.model}" not found in models`)
  if (!config.auth) warnings.push("No auth configured — all routes are public")
  if (!existsSync(join(rootDir, "node_modules"))) warnings.push("node_modules not installed (run bun install)")

  if (warnings.length > 0) {
    w(``)
    w(`## Warnings`)
    for (const wr of warnings) w(`- ⚠️  ${wr}`)
  }

  w(``)
  w(`---`)
  w(`Generated by \`zorux snapshot\``)
  w(`Run \`zorux explain\` for full generation plan`)

  const content = lines.join("\n")
  const dotDir = join(rootDir, ".zorux")
  mkdirSync(dotDir, { recursive: true })
  writeFileSync(join(dotDir, "snapshot.md"), content, "utf-8")

  const tokens = Math.ceil(content.length / 4)
  console.log(`\n  📸 Snapshot written to .zorux/snapshot.md (~${tokens} tokens)\n`)
}
